# Generated by Django 5.2.5 on 2025-11-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('estilista', 'Estilista'), ('recepcionista', 'Recepcionista'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
