# Generated by Django 5.2.8 on 2025-11-19 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('estilista', 'Estilista'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=15),
        ),
        migrations.CreateModel(
            name='AccionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción Historial',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
